#ifndef TY_MODELS_BUSINESS_DEFAULT_SOLVER_CONFIG
#define TY_MODELS_BUSINESS_DEFAULT_SOLVER_CONFIG

const char * DEFAULT_SOLVER_CONFIG =
"##############################################\n"
"# Meteo related parameters\n"
"##############################################\n"
"[METEO]\n"
"\n"
"# Atmospheric pressure in pascal [type: double]\n"
"# XXX 101325 dans TYAtmosphere.h\n"
"AtmosPressure=101300.\n"
"# Temperature in degres celsius [type: double]\n"
"AtmosTemperature=20.\n"
"# Hygrometry percent [type: double]\n"
"# XXX 70 dans TYAtmosphere.h\n"
"AtmosHygrometry=60.\n"
"# Temperature gradient [type : double]\n"
"AnalyticGradC=0.\n"
"# Vertical wind speed gradient [type: double]\n"
"AnalyticGradV=0.\n"
"# Wind direction 0 means from north to south [type: double]\n"
"WindDirection=0.\n"
"\n"
"\n"
"##############################################\n"
"# Acoustic ray tracer related parameters\n"
"##############################################\n"
"[ACOUSTICRAYTRACER]\n"
"\n"
"# Ray tracing order propagation (0=From, 1=from receptor, 2=auto) [int]\n"
"RayTracingOrder=0\n"
"# Sampler model 0=random, 1=uniform v1, 2= uniform v2, 3=horizontal [int]\n"
"Discretization=2\n"
"# Number of rays per source [int]\n"
"NbRaysPerSource=100000\n"
"# Maximum ray length in meter [float]\n"
"MaxLength=5000\n"
"# Receptor radius in meter [float]\n"
"SizeReceiver=2.\n"
"# Accelerating structure parameter (0=brut force, 1=grid, 2=BVH, 3=KDTree) [int]\n"
"Accelerator=3\n"
"# Maximal depth search for BVH or KDTree [int]\n"
"MaxTreeDepth=12\n"
"# Minimum dihedral angle to add a diffraction cylinder [float]\n"
"AngleDiffMin=5.\n"
"# Diffraction ridge size in meter [float]\n"
"CylindreThick=0.3\n"
"# Maximum events number for a ray [int]\n"
"MaxProfondeur=10\n"
"# Allow ground reflections [bool]\n"
"UseSol=1\n"
"# Maximum reflections events for a ray [int]\n"
"MaxReflexion=2\n"
"# Maximum diffraction events for a ray [int]\n"
"MaxDiffraction=2\n"
"# Use random sampler instead of regular distribution [bool]\n"
"DiffractionUseRandomSampler=0\n"
"# Number of ray thrown after diffraction (0 = based on source sampling, >0 = forced) [int]\n"
"NbRayWithDiffraction=0\n"
"# Drop down number of rays thrown after a diffraction [bool]\n"
"DiffractionDropDownNbRays=0\n"
"# Do not create rays outside the correct angle [bool]\n"
"DiffractionFilterRayAtCreation=1\n"
"# Allow use of path length difference validation [bool]\n"
"UsePathDifValidation=0\n"
"# Maximum path length difference in meter (25 meters for 25 dB, 8 meters for 20 dB) [float]\n"
"MaxPathDifference=25.\n"
"# Allow suppressing rays passing to far from the ridge [bool]\n"
"DiffractionUseDistanceAsFilter=1\n"
"# Keep invalid rays [bool]\n"
"KeepDebugRay=0\n"
"# Use of post-filters [bool]\n"
"UsePostFilters=1\n"
"#\n"
"##############################################\n"
"# Debugging related parameters\n"
"#\n"
"# Only considered by the acoustic ray tracer\n"
"##############################################\n"
"[DEBUG]\n"
"# allow use of closeEventSelector [bool]\n"
"DebugUseCloseEventSelector=1\n"
"# allow use of diffraction angle selector [bool]\n"
"DebugUseDiffractionAngleSelector=1\n"
"# allow use of diffraction path length selector [bool]\n"
"DebugUseDiffractionPathSelector=1\n"
"# allow use of Fermat selector [bool]\n"
"DebugUseFermatSelector=1\n"
"# allow use of (doubled) faces selector [bool]\n"
"DebugUseFaceSelector=1\n"
"\n"
"##############################################\n"
"# Analytic ray tracer related parameters\n"
"#\n"
"# Only considered by the ANIME3D solver\n"
"##############################################\n"
"[ANALYTICRAYTRACER]\n"
"# Sampler model 1=horizontal, 2=vertical, 3=uniform v1, 4=uniform v2 [int]\n"
"CurveRaySampler=1\n"
"# Start vertical angle (theta) [float]\n"
"InitialAngleTheta=0.\n"
"# Final vertical angle (theta) [float]\n"
"FinalAngleTheta=0.\n"
"# Start horizontal angle (phi) [float]\n"
"InitialAnglePhi=0.\n"
"# Final horizontal angle (phi) [float]\n"
"FinalAnglePhi=360.\n"
"# Number of rays per source [int]\n"
"AnalyticNbRay=20\n"
"# Propagation time in second [double]\n"
"AnalyticTMax=10.\n"
"# Time step in second [double]\n"
"AnalyticH=0.1\n"
"# Maximum length propagation [double]\n"
"AnalyticDMax=3000\n"
"\n"
"##############################################\n"
"# Geometric transformer related parameters\n"
"#\n"
"# Only considered by the ANIME3D solver\n"
"##############################################\n"
"[GEOMTRANSFORMER]\n"
"# Transformation method (1 is the only [good] response) [int]\n"
"AnalyticTypeTransfo=1\n"
"# Altimetry refinement parameter [float]\n"
"MeshRefinementValue=0\n"
"# Restore modified altimetry after computing [bool]\n"
"#RestitModifiedGeom=0\n"
"\n"
"##############################################\n"
"# Preprocessing related parameters\n"
"##############################################\n"
"[PREPROCESSING]\n"
"# Source-receptor minimal distance in meters [float]\n"
"MinSRDistance=0.3\n"
"\n"
"##############################################\n"
"# Default solver related parameters\n"
"#\n"
"# Only considered by the default solver\n"
"##############################################\n"
"[DEFAULTSOLVER]\n"
"NbThreads=4\n"
"# Use of real ground (0) or totally reflective ground (1) [bool]\n"
"UseRealGround=1\n"
"# Takes vegetation into account [bool]\n"
"#UseVegetation=0\n"
"# Takes screens into account [bool]\n"
"UseScreen=1\n"
"# Lateral diffractions computing (if screens on) [bool]\n"
"UseLateralDiffraction=1\n"
"# Takes reflections in account (first order only) [bool]\n"
"UseReflection=1\n"
"# Propagation conditions (non refracting / downward conditions (ISO 9613)) [bool]\n"
"PropaConditions=0\n"
"# H1 parameter (ISO 9613 downward conditions) [float]\n"
"H1parameter=10.\n"
"# Energetic (p² summation) or interference (p summation) [bool]\n"
"ModSummation=0\n"
"\n"
"##############################################\n"
"# ANIME3D solver related parameters\n"
"#\n"
"# Only considered by the ANIME3D solver\n"
"##############################################\n"
"[ANIME3DSOLVER]\n"
"# Takes meteo in account [bool]\n"
"UseMeteo=0\n"
"# Use Fresnel area [bool]\n"
"UseFresnelArea=0\n"
"# Value of relative uncertainty [float]\n"
"Anime3DSigma=0.\n"
"# Force 'C' parameter to 0 or 1 (will be computed from totalRayLength for any other value) [int]\n"
"Anime3DForceC=1\n"
;

#endif
