#include "init_registry.h"
#include "Tympan/Tools/OPrototype.h"

#include "Tympan/MetierSolver/DataManagerCore/TYElement.h"
#include "Tympan/MetierSolver/DataManagerMetier/Site/TYTopographie.h"
#include "Tympan/MetierSolver/DataManagerMetier/Site/TYInfrastructure.h"
#include "Tympan/MetierSolver/DataManagerMetier/Site/TYSiteNode.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltInfrastructure/TYDalle.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltInfrastructure/TYEcran.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltInfrastructure/TYBatiment.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltInfrastructure/TYEtage.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltInfrastructure/TYMachine.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltInfrastructure/TYMur.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltInfrastructure/TYRoute.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltInfrastructure/TYMurElement.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltInfrastructure/TYReseauTransport.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltInfrastructure/TYParoi.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltMateriaux/TYMateriauConstruction.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltMateriaux/TYVegetation.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltMateriaux/TYAtmosphere.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltMateriaux/TYSol.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeometrique/TYPoint.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeometrique/TYRepere.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeometrique/TYBox.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeometrique/TYSegment.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeometrique/TYGeometryNode.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeometrique/TYPolygon.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeometrique/TYFaceSet.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeometrique/TYRectangle.h"
#include "Tympan/MetierSolver/DataManagerMetier/Commun/TYPalette.h"
#include "Tympan/MetierSolver/DataManagerMetier/Commun/TYPanel.h"
#include "Tympan/MetierSolver/DataManagerMetier/Commun/TYBoundaryNoiseMap.h"
#include "Tympan/MetierSolver/DataManagerMetier/Commun/TYLinearMaillage.h"
#include "Tympan/MetierSolver/DataManagerMetier/Commun/TYPointControl.h"
#include "Tympan/MetierSolver/DataManagerMetier/Commun/TYPointCalcul.h"
#include "Tympan/MetierSolver/DataManagerMetier/Commun/TYResultat.h"
#include "Tympan/MetierSolver/DataManagerMetier/Commun/TYRectangularMaillage.h"
#include "Tympan/MetierSolver/DataManagerMetier/Commun/TYProjet.h"
#include "Tympan/MetierSolver/DataManagerMetier/Commun/TYMaillage.h"
#include "Tympan/MetierSolver/DataManagerMetier/Commun/TYCalcul.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltTopographique/TYAltimetrie.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltTopographique/TYPlanEau.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltTopographique/TYCoursEau.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltTopographique/TYTerrain.h"
#include "Tympan/MetierSolver/DataManagerMetier/EltTopographique/TYCourbeNiveau.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantAcoustique/TYSource.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantAcoustique/TYDirectivite.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantAcoustique/TYSpectre.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantAcoustique/TYSourceLineic.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantAcoustique/TYSourceCheminee.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantAcoustique/TYUserSourcePonctuelle.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantAcoustique/TYSourceSurfacic.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantAcoustique/TYSourcePonctuelle.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantAcoustique/TYSourceBafflee.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantAcoustique/TYTrafic.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantAcoustique/TYAttenuateur.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYChemineeSurface.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticSurfaceNode.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticVolume.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticSurface.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticRectangle.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticSemiCylinder.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticRectangleNode.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticCylinder.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticBox.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticSemiCircle.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticVolumeNode.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticCircle.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticPolygon.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticLine.h"
#include "Tympan/MetierSolver/DataManagerMetier/ComposantGeoAcoustique/TYAcousticFaceSet.h"

namespace tympan
{

void init_registry()
{
    // MetierSolver/DataManagerCore
    OPrototype::add_factory("TYElement", std::move(build_factory<TYElement>()));
    // Metier/Solver/DataManagerMetier/Site
    OPrototype::add_factory("TYTopographie", std::move(build_factory<TYTopographie>()));
    OPrototype::add_factory("TYInfrastructure", std::move(build_factory<TYInfrastructure>()));
    OPrototype::add_factory("TYSiteNode", std::move(build_factory<TYSiteNode>()));
    // MetierSolver/DataManagerMetier/EltInfrastructure
    OPrototype::add_factory("TYDalle", std::move(build_factory<TYDalle>()));
    OPrototype::add_factory("TYEcran", std::move(build_factory<TYEcran>()));
    OPrototype::add_factory("TYBatiment", std::move(build_factory<TYBatiment>()));
    OPrototype::add_factory("TYEtage", std::move(build_factory<TYEtage>()));
    OPrototype::add_factory("TYMachine", std::move(build_factory<TYMachine>()));
    OPrototype::add_factory("TYMur", std::move(build_factory<TYMur>()));
    OPrototype::add_factory("TYRoute", std::move(build_factory<TYRoute>()));
    OPrototype::add_factory("TYMurElement", std::move(build_factory<TYMurElement>()));
    OPrototype::add_factory("TYReseauTransport", std::move(build_factory<TYReseauTransport>()));
    OPrototype::add_factory("TYParoi", std::move(build_factory<TYParoi>()));
    // MetierSolver/DataManagerMetier/EltMateriaux
    OPrototype::add_factory("TYMateriauConstruction", std::move(build_factory<TYMateriauConstruction>()));
    OPrototype::add_factory("TYVegetation", std::move(build_factory<TYVegetation>()));
    OPrototype::add_factory("TYAtmosphere", std::move(build_factory<TYAtmosphere>()));
    OPrototype::add_factory("TYSol", std::move(build_factory<TYSol>()));
    // MetierSolver/DataManagerMetier/ComposantGeometrique
    OPrototype::add_factory("TYPoint", std::move(build_factory<TYPoint>()));
    OPrototype::add_factory("TYRepere", std::move(build_factory<TYRepere>()));
    OPrototype::add_factory("TYBox", std::move(build_factory<TYBox>()));
    OPrototype::add_factory("TYSegment", std::move(build_factory<TYSegment>()));
    OPrototype::add_factory("TYGeometryNode", std::move(build_factory<TYGeometryNode>()));
    OPrototype::add_factory("TYPolygon", std::move(build_factory<TYPolygon>()));
    OPrototype::add_factory("TYFaceSet", std::move(build_factory<TYFaceSet>()));
    OPrototype::add_factory("TYRectangle", std::move(build_factory<TYRectangle>()));
    // MetierSolver/DataManagerMetier/Commun
    OPrototype::add_factory("TYPalette", std::move(build_factory<TYPalette>()));
    OPrototype::add_factory("TYPanel", std::move(build_factory<TYPanel>()));
    OPrototype::add_factory("TYBoundaryNoiseMap", std::move(build_factory<TYBoundaryNoiseMap>()));
    OPrototype::add_factory("TYLinearMaillage", std::move(build_factory<TYLinearMaillage>()));
    OPrototype::add_factory("TYPointControl", std::move(build_factory<TYPointControl>()));
    OPrototype::add_factory("TYPointCalcul", std::move(build_factory<TYPointCalcul>()));
    OPrototype::add_factory("TYResultat", std::move(build_factory<TYResultat>()));
    OPrototype::add_factory("TYRectangularMaillage", std::move(build_factory<TYRectangularMaillage>()));
    OPrototype::add_factory("TYProjet", std::move(build_factory<TYProjet>()));
    OPrototype::add_factory("TYMaillage", std::move(build_factory<TYMaillage>()));
    OPrototype::add_factory("TYCalcul", std::move(build_factory<TYCalcul>()));
    // MetierSolver/DataManagerMetier/EltTopographique
    OPrototype::add_factory("TYAltimetrie", std::move(build_factory<TYAltimetrie>()));
    OPrototype::add_factory("TYPlanEau", std::move(build_factory<TYPlanEau>()));
    OPrototype::add_factory("TYCoursEau", std::move(build_factory<TYCoursEau>()));
    OPrototype::add_factory("TYTerrain", std::move(build_factory<TYTerrain>()));
    OPrototype::add_factory("TYCourbeNiveau", std::move(build_factory<TYCourbeNiveau>()));
    // MetierSolver/DataManagerMetier/ComposantAcoustique
    OPrototype::add_factory("TYSource", std::move(build_factory<TYSource>()));
    OPrototype::add_factory("TYDirectivite", std::move(build_factory<TYDirectivite>()));
    OPrototype::add_factory("TYSpectre", std::move(build_factory<TYSpectre>()));
    OPrototype::add_factory("TYSourceLineic", std::move(build_factory<TYSourceLineic>()));
    OPrototype::add_factory("TYSourceCheminee", std::move(build_factory<TYSourceCheminee>()));
    OPrototype::add_factory("TYUserSourcePonctuelle", std::move(build_factory<TYUserSourcePonctuelle>()));
    OPrototype::add_factory("TYSourceSurfacic", std::move(build_factory<TYSourceSurfacic>()));
    OPrototype::add_factory("TYSourcePonctuelle", std::move(build_factory<TYSourcePonctuelle>()));
    OPrototype::add_factory("TYSourceBafflee", std::move(build_factory<TYSourceBafflee>()));
    OPrototype::add_factory("TYTrafic", std::move(build_factory<TYTrafic>()));
    OPrototype::add_factory("TYAttenuateur", std::move(build_factory<TYAttenuateur>()));
    // MetierSolver/DataManagerMetier/ComposantGeoAcoustique
    OPrototype::add_factory("TYChemineeSurface", std::move(build_factory<TYChemineeSurface>()));
    OPrototype::add_factory("TYAcousticSurfaceNode", std::move(build_factory<TYAcousticSurfaceNode>()));
    OPrototype::add_factory("TYAcousticVolume", std::move(build_factory<TYAcousticVolume>()));
    OPrototype::add_factory("TYAcousticSurface", std::move(build_factory<TYAcousticSurface>()));
    OPrototype::add_factory("TYAcousticRectangle", std::move(build_factory<TYAcousticRectangle>()));
    OPrototype::add_factory("TYAcousticSemiCylinder", std::move(build_factory<TYAcousticSemiCylinder>()));
    OPrototype::add_factory("TYAcousticRectangleNode", std::move(build_factory<TYAcousticRectangleNode>()));
    OPrototype::add_factory("TYAcousticCylinder", std::move(build_factory<TYAcousticCylinder>()));
    OPrototype::add_factory("TYAcousticBox", std::move(build_factory<TYAcousticBox>()));
    OPrototype::add_factory("TYAcousticSemiCircle", std::move(build_factory<TYAcousticSemiCircle>()));
    OPrototype::add_factory("TYAcousticVolumeNode", std::move(build_factory<TYAcousticVolumeNode>()));
    OPrototype::add_factory("TYAcousticCircle", std::move(build_factory<TYAcousticCircle>()));
    OPrototype::add_factory("TYAcousticPolygon", std::move(build_factory<TYAcousticPolygon>()));
    OPrototype::add_factory("TYAcousticLine", std::move(build_factory<TYAcousticLine>()));
    OPrototype::add_factory("TYAcousticFaceSet", std::move(build_factory<TYAcousticFaceSet>()));

    // These classes weren't registered initially. Make sure they really don't need
    // to be.
//    OPrototype::add_factory("TYUserSrcRegime", std::move(build_factory<TYUserSrcRegime>()));
//    OPrototype::add_factory("TYRay", std::move(build_factory<TYRay>()));
//    OPrototype::add_factory("TYRegime", std::move(build_factory<TYRegime>()));
}

}
