.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Logilab <contact@logilab.fr>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CODETYMPAN SECTION "September 10, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
code-tympan \- program run acoustic simulations
.SH SYNOPSIS
.B code-tympan
.SH DESCRIPTION
This manual page documents briefly the
.B code-tympan
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBcode-tympan\fP is a program that allows to deal with 3D realistic geometries
and has a convenient GUI to help engineers build 3D models and to achieve
analysis needed in environmental noise studies. It also gives access to methods
developed in the R&D division of EDF.
.SH SEE ALSO
.br
For more information, see online documentation at http://www.code-tympan.org/.
